[Desktop Entry]
Name=dark_extra
Type=X-GNOME-Metatheme
Comment=

[X-GNOME-Metatheme]
GtkTheme=Numix
MetacityTheme=Numix
IconTheme=Numix
GtkColorScheme=fg_color:#fdfdf6f6e3e3,bg_color:#444444444444,text_color:#fdfdf6f6e3e3,base_color:#444444444444,selected_fg_color:#ffffffffffff,selected_bg_color:#00007676a1a1,tooltip_fg_color:#eeeeeeeeeeee,tooltip_bg_color:#444444444444
CursorTheme=default
CursorSize=18
