[Desktop Entry]
Name=meme
Type=X-GNOME-Metatheme
Comment=

[X-GNOME-Metatheme]
GtkTheme=Ambiance-Aqua-Pro
MetacityTheme=Ambiance-Aqua-Pro
IconTheme=Vivacious-Full-Dark-Blue
GtkColorScheme=fg_color:#f2f2f2f2f2f2,bg_color:#454545454545,text_color:#f2f2f2f2f2f2,base_color:#444444444444,selected_fg_color:#ffffffffffff,selected_bg_color:#fe2956354cce,tooltip_fg_color:#ffffffffffff,tooltip_bg_color:#000000000000
CursorTheme=DMZ-White
CursorSize=24
BackgroundImage=/home/meme/Pictures/tux-linux-4k.jpg
